### ISSUE TITLE
Accessing PrometheOS bin

### ISSUE THREAD

**Issue by falconmick** [dtomcat/AdvancedXeniumProgrammer#1]
Hey!

very new to Xbox modding scene, was wondering how people typically get a copy of PrometheOS‘a bin? From what I can see from quick googling everyone uses xbins pandora but using a random exe to download files kinda has all the hallmarks of sketchiness and I’m just confused why it isn’t just a web portal which makes me unsure if it’s the correct approach.

cheers

**Comment by falconmick** [comment]
also not to open 2 issues, what is the point of the 3.3v 2 pin slot? I cannot see it plugged into anything so I am at a loss

**Comment by dtomcat** [comment]
PrometheOS isn’t my work and that’s just how it’s distributed. I can say that people download it with how you explained above without issue… but I understand your concern…. The 3.3v connects pi’s 3.3v to the OX. I just carried it over from original design… you can just bridge it on PCB with solder instead of a pin header if you like

**Comment by dtomcat** [comment]
I’ll close this since you answered the question :). Sorry I can’t help more   I was advised not to host it on my GitHub.

**Comment by falconmick** [comment]
Cheers :)

I've got a pcb in the mail and the components are also in the mail so I'm looking forward to the build!



Oh if you have the 3d cad model for the case still kicking around I would love to re-mix it to update the text to be additive to the top so I can use my printers filament swapping to make nice crisp letters :)
